/**
 * A baked square of ground, loaded for the site a plan sits on.
 *
 * Height is not stored in the game; it is generated by walking a tree of
 * terrain affectors, which costs milliseconds per sample. So it is baked
 * offline by `tre-extract terrain` and the browser only reads the result --
 * an int16 heightfield in decimetres plus one byte of flags per sample.
 *
 * Sampling is bilinear between the baked points rather than nearest. The
 * engine drapes a triangle fan over its poles and a nearest-sample lookup
 * would stair-step visibly at 8 m spacing, which reads as blocky ground
 * rather than as the smooth dunes actually there.
 */

const ASSET_BASE = process.env.NEXT_PUBLIC_ASSET_BASE ?? '/assets';

export interface TerrainTileMeta {
  planet: string;
  originX: number;
  originZ: number;
  centreX: number;
  centreZ: number;
  span: number;
  spacing: number;
  samples: number;
  minHeight: number;
  maxHeight: number;
  height: string;
  flags: string;
}

/** Flag bits, as written by the bake. */
export const FLAG_WATER = 0x01;
export const FLAG_SLOPE = 0x02;

export class TerrainTile {
  constructor(
    readonly meta: TerrainTileMeta,
    /** Decimetres, row-major from the south-west corner. */
    private readonly heights: Int16Array,
    private readonly flags: Uint8Array,
  ) {}

  /** Sample index for a world coordinate, unclamped so callers can test range. */
  private index(world: number, origin: number): number {
    return (world - origin) / this.meta.spacing;
  }

  contains(x: number, z: number): boolean {
    const { samples } = this.meta;
    const cx = this.index(x, this.meta.originX);
    const cz = this.index(z, this.meta.originZ);
    return cx >= 0 && cz >= 0 && cx <= samples - 1 && cz <= samples - 1;
  }

  /** Metres above sea level, bilinear between baked samples. */
  heightAt(x: number, z: number): number {
    const { samples } = this.meta;
    const fx = Math.min(Math.max(this.index(x, this.meta.originX), 0), samples - 1);
    const fz = Math.min(Math.max(this.index(z, this.meta.originZ), 0), samples - 1);
    const x0 = Math.floor(fx);
    const z0 = Math.floor(fz);
    const x1 = Math.min(x0 + 1, samples - 1);
    const z1 = Math.min(z0 + 1, samples - 1);
    const tx = fx - x0;
    const tz = fz - z0;

    const h00 = this.heights[z0 * samples + x0];
    const h10 = this.heights[z0 * samples + x1];
    const h01 = this.heights[z1 * samples + x0];
    const h11 = this.heights[z1 * samples + x1];
    const top = h00 + (h10 - h00) * tx;
    const bottom = h01 + (h11 - h01) * tx;
    return (top + (bottom - top) * tz) / 10;
  }

  /** Flags at the nearest baked sample. These are per-cell, so no interpolation. */
  flagsAt(x: number, z: number): number {
    const { samples } = this.meta;
    const cx = Math.min(Math.max(Math.round(this.index(x, this.meta.originX)), 0), samples - 1);
    const cz = Math.min(Math.max(Math.round(this.index(z, this.meta.originZ)), 0), samples - 1);
    return this.flags[cz * samples + cx];
  }

  isWater(x: number, z: number): boolean {
    return (this.flagsAt(x, z) & FLAG_WATER) !== 0;
  }

  /** Raw access for building a mesh, which wants the grid rather than points. */
  get grid(): { samples: number; spacing: number; heights: Int16Array; flags: Uint8Array } {
    return {
      samples: this.meta.samples,
      spacing: this.meta.spacing,
      heights: this.heights,
      flags: this.flags,
    };
  }
}

/** Name a tile the way the bake names it, so a site resolves without an index. */
export function tileName(planet: string, x: number, z: number): string {
  return `${planet}_${Math.round(x)}_${Math.round(z)}`;
}

export async function loadTerrainTile(name: string): Promise<TerrainTile | null> {
  const base = `${ASSET_BASE}/terrain/${name}`;
  try {
    const metaResponse = await fetch(`${base}.json`);
    if (!metaResponse.ok) return null;
    const meta = (await metaResponse.json()) as TerrainTileMeta;

    const [heightBuffer, flagBuffer] = await Promise.all([
      fetch(`${ASSET_BASE}/terrain/${meta.height}`).then((r) => r.arrayBuffer()),
      fetch(`${ASSET_BASE}/terrain/${meta.flags}`).then((r) => r.arrayBuffer()),
    ]);

    const expected = meta.samples * meta.samples;
    const heights = new Int16Array(heightBuffer);
    const flags = new Uint8Array(flagBuffer);
    if (heights.length !== expected || flags.length !== expected) {
      // A truncated tile would render as a torn mesh with a plausible-looking
      // corner, which is worse than no terrain at all.
      console.error(
        `terrain tile ${name} is the wrong size: ${heights.length}/${flags.length} ` +
          `samples, expected ${expected}`,
      );
      return null;
    }
    return new TerrainTile(meta, heights, flags);
  } catch {
    // No tile baked for this site. The planner falls back to flat ground.
    return null;
  }
}
