/**
 * A baked square of ground, loaded for the site a plan sits on.
 *
 * Height is not stored in the game; it is generated by walking a tree of
 * terrain affectors, which costs milliseconds per sample. So it is baked
 * offline by `tre-extract terrain` and the browser only reads the result --
 * an int16 heightfield in decimetres plus one byte of flags per sample.
 *
 * Sampling is bilinear between the baked points rather than nearest. The
 * engine drapes a triangle fan over its poles and a nearest-sample lookup
 * would stair-step visibly at 8 m spacing, which reads as blocky ground
 * rather than as the smooth dunes actually there.
 */

const ASSET_BASE = process.env.NEXT_PUBLIC_ASSET_BASE ?? '/assets';

export interface TerrainTileMeta {
  planet: string;
  originX: number;
  originZ: number;
  centreX: number;
  centreZ: number;
  span: number;
  spacing: number;
  samples: number;
  minHeight: number;
  maxHeight: number;
  height: string;
  flags: string;
  /**
   * Metres above sea level that this tile's zero means, when it has been
   * rebased onto a site. Absent on a tile that is already in world terms.
   */
  datum?: number;
}

/** Flag bits, as written by the bake. */
export const FLAG_WATER = 0x01;
export const FLAG_SLOPE = 0x02;

export class TerrainTile {
  constructor(
    readonly meta: TerrainTileMeta,
    /** Decimetres, row-major from the south-west corner. */
    private readonly heights: Int16Array,
    private readonly flags: Uint8Array,
  ) {}

  /** Sample index for a world coordinate, unclamped so callers can test range. */
  private index(world: number, origin: number): number {
    return (world - origin) / this.meta.spacing;
  }

  contains(x: number, z: number): boolean {
    const { samples } = this.meta;
    const cx = this.index(x, this.meta.originX);
    const cz = this.index(z, this.meta.originZ);
    return cx >= 0 && cz >= 0 && cx <= samples - 1 && cz <= samples - 1;
  }

  /** Metres above sea level, bilinear between baked samples. */
  heightAt(x: number, z: number): number {
    const { samples } = this.meta;
    const fx = Math.min(Math.max(this.index(x, this.meta.originX), 0), samples - 1);
    const fz = Math.min(Math.max(this.index(z, this.meta.originZ), 0), samples - 1);
    const x0 = Math.floor(fx);
    const z0 = Math.floor(fz);
    const x1 = Math.min(x0 + 1, samples - 1);
    const z1 = Math.min(z0 + 1, samples - 1);
    const tx = fx - x0;
    const tz = fz - z0;

    const h00 = this.heights[z0 * samples + x0];
    const h10 = this.heights[z0 * samples + x1];
    const h01 = this.heights[z1 * samples + x0];
    const h11 = this.heights[z1 * samples + x1];
    const top = h00 + (h10 - h00) * tx;
    const bottom = h01 + (h11 - h01) * tx;
    return (top + (bottom - top) * tz) / 10;
  }

  /** Flags at the nearest baked sample. These are per-cell, so no interpolation. */
  flagsAt(x: number, z: number): number {
    const { samples } = this.meta;
    const cx = Math.min(Math.max(Math.round(this.index(x, this.meta.originX)), 0), samples - 1);
    const cz = Math.min(Math.max(Math.round(this.index(z, this.meta.originZ)), 0), samples - 1);
    return this.flags[cz * samples + cx];
  }

  isWater(x: number, z: number): boolean {
    return (this.flagsAt(x, z) & FLAG_WATER) !== 0;
  }

  /** Raw access for building a mesh, which wants the grid rather than points. */
  get grid(): { samples: number; spacing: number; heights: Int16Array; flags: Uint8Array } {
    return {
      samples: this.meta.samples,
      spacing: this.meta.spacing,
      heights: this.heights,
      flags: this.flags,
    };
  }
}

// ---------------------------------------------------------------------------
// Cutting a site out of the whole-planet bake.
//
// A site used to need its own `tre-extract terrain --centre X,Z` run, so any
// coordinate nobody had baked showed the flat grid -- which is every coordinate
// but one. The whole-planet bake covers the entire world at the same 8 m
// spacing, so there is nothing left to bake per site: the ground for a plan is
// a window cut out of it.
//
// Planet tiles are cached across sites. Moving a plan 200 m usually needs the
// same one or two 128 KB tiles, and re-fetching them on every nudge would make
// dragging a site feel like loading a level.
// ---------------------------------------------------------------------------

/** What `planet.json` says. Only the fields this cut needs are described. */
interface PlanetTileMeta {
  mapWidth: number;
  spacing: number;
  samples: number;
  tileSamples: number;
  tiles: number;
  originX: number;
  originZ: number;
}

interface PlanetTileData {
  heights: Int16Array;
  flags: Uint8Array;
  width: number;
}

const planetMetaCache = new Map<string, Promise<PlanetTileMeta | null>>();
const planetTileCache = new Map<string, Promise<PlanetTileData | null>>();

function planetMeta(planet: string): Promise<PlanetTileMeta | null> {
  let entry = planetMetaCache.get(planet);
  if (!entry) {
    entry = (async () => {
      const response = await fetch(`${ASSET_BASE}/terrain/${planet}/planet.json`);
      if (!response.ok) return null;
      return (await response.json()) as PlanetTileMeta;
    })().catch(() => null);
    planetMetaCache.set(planet, entry);
  }
  return entry;
}

function planetTile(
  planet: string,
  tileZ: number,
  tileX: number,
  meta: PlanetTileMeta,
): Promise<PlanetTileData | null> {
  const key = `${planet}/${tileZ}_${tileX}`;
  let entry = planetTileCache.get(key);
  if (!entry) {
    entry = (async () => {
      const base = `${ASSET_BASE}/terrain/${planet}/${tileZ}_${tileX}`;
      const [heightResponse, flagResponse] = await Promise.all([
        fetch(`${base}.height`),
        fetch(`${base}.flags`),
      ]);
      if (!heightResponse.ok || !flagResponse.ok) return null;
      const heights = new Int16Array(await heightResponse.arrayBuffer());
      const flags = new Uint8Array(await flagResponse.arrayBuffer());
      // The last row and column of tiles are short when the planet's sample
      // count is not a whole number of tiles, so the size is derived rather
      // than assumed -- a wrong width would shear the ground diagonally.
      const width = Math.min(meta.tileSamples, meta.samples - tileX * meta.tileSamples);
      const height = Math.min(meta.tileSamples, meta.samples - tileZ * meta.tileSamples);
      if (heights.length !== width * height || flags.length !== width * height) {
        console.error(
          `planet tile ${key} is the wrong size: ${heights.length}/${flags.length}, ` +
            `expected ${width * height}`,
        );
        return null;
      }
      return { heights, flags, width };
    })().catch(() => null);
    planetTileCache.set(key, entry);
  }
  return entry;
}

/**
 * The ground around a site, cut out of the whole-planet bake.
 *
 * `span` is the width of the square in metres. It is snapped outward to the
 * planet's own sample grid so the samples returned are the baked ones rather
 * than an interpolation of them, and clamped to the planet, so a site near the
 * edge of the world gets a window that shifts inwards instead of a torn one.
 *
 * The tile comes back in the PLANNER'S space, not the world's, because that is
 * the only space the planner has. A plan's structures are stored relative to
 * its site and blockers are re-centred onto it, so a tile carrying world
 * origins would be indexed with local coordinates, clamp to its own corner and
 * hand every building on the site the same altitude -- which is exactly a
 * building floating over the ground it is supposed to stand on.
 *
 * So two things are rebased. Horizontally, the origin is stated relative to the
 * site, so local (0, 0) is the site itself. Vertically, heights are relative to
 * the ground AT the site, so y = 0 is what a planner draws its buildable circle
 * and its grid on. The world altitude that zero stands for is kept in `datum`,
 * so nothing is actually lost.
 */
export async function loadSiteTerrain(
  planet: string,
  centreX: number,
  centreZ: number,
  span: number,
): Promise<TerrainTile | null> {
  const meta = await planetMeta(planet);
  if (!meta) return null;

  const { spacing } = meta;
  const samples = Math.min(Math.round(span / spacing) + 1, meta.samples);
  const clampStart = (world: number, origin: number) =>
    Math.min(
      Math.max(Math.round((world - span / 2 - origin) / spacing), 0),
      meta.samples - samples,
    );
  const col0 = clampStart(centreX, meta.originX);
  const row0 = clampStart(centreZ, meta.originZ);

  const tileZ0 = Math.floor(row0 / meta.tileSamples);
  const tileZ1 = Math.floor((row0 + samples - 1) / meta.tileSamples);
  const tileX0 = Math.floor(col0 / meta.tileSamples);
  const tileX1 = Math.floor((col0 + samples - 1) / meta.tileSamples);

  const loaded = new Map<string, PlanetTileData>();
  const pending: Promise<void>[] = [];
  for (let tileZ = tileZ0; tileZ <= tileZ1; tileZ += 1) {
    for (let tileX = tileX0; tileX <= tileX1; tileX += 1) {
      pending.push(
        planetTile(planet, tileZ, tileX, meta).then((data) => {
          if (data) loaded.set(`${tileZ}_${tileX}`, data);
        }),
      );
    }
  }
  await Promise.all(pending);
  // Every tile the window touches has to be there. A partial answer would draw
  // real ground beside a flat slab and look like terrain rather than a failure.
  const wanted = (tileZ1 - tileZ0 + 1) * (tileX1 - tileX0 + 1);
  if (loaded.size !== wanted) return null;

  const heights = new Int16Array(samples * samples);
  const flags = new Uint8Array(samples * samples);
  for (let row = 0; row < samples; row += 1) {
    const worldRow = row0 + row;
    const tileZ = Math.floor(worldRow / meta.tileSamples);
    const localRow = worldRow - tileZ * meta.tileSamples;
    for (let col = 0; col < samples; col += 1) {
      const worldCol = col0 + col;
      const tileX = Math.floor(worldCol / meta.tileSamples);
      const tile = loaded.get(`${tileZ}_${tileX}`);
      if (!tile) continue;
      const source = localRow * tile.width + (worldCol - tileX * meta.tileSamples);
      const target = row * samples + col;
      heights[target] = tile.heights[source];
      flags[target] = tile.flags[source];
    }
  }

  // The window is snapped to the planet's sample grid, so its origin is up to
  // one sample away from the site. Stating it relative to the site rather than
  // assuming the site is at the centre keeps the lookup exact.
  const originX = meta.originX + col0 * spacing - centreX;
  const originZ = meta.originZ + row0 * spacing - centreZ;

  /**
   * The ground the site itself stands on, which becomes y = 0.
   *
   * Read through the tile's own bilinear sampling rather than off the nearest
   * sample, because that is how every other height on this tile will be read.
   * The site almost never lands on a sample -- it is a waypoint, not a grid
   * point -- so taking the nearest one instead put the whole plan out by
   * whatever the ground does in between, measured at 3.7 m on the first site
   * tried, with the site itself reading -4.5 m rather than 0.
   */
  const worldOriginX = meta.originX + col0 * spacing;
  const worldOriginZ = meta.originZ + row0 * spacing;
  const worldMeta: TerrainTileMeta = {
    planet,
    originX: worldOriginX,
    originZ: worldOriginZ,
    centreX: worldOriginX + ((samples - 1) * spacing) / 2,
    centreZ: worldOriginZ + ((samples - 1) * spacing) / 2,
    span: (samples - 1) * spacing,
    spacing,
    samples,
    minHeight: 0,
    maxHeight: 0,
    height: `${planet}/cut`,
    flags: `${planet}/cut`,
  };
  const datumDm = Math.round(
    new TerrainTile(worldMeta, heights, flags).heightAt(centreX, centreZ) * 10,
  );
  for (let i = 0; i < heights.length; i += 1) heights[i] -= datumDm;

  let lowest = Infinity;
  let highest = -Infinity;
  for (let i = 0; i < heights.length; i += 1) {
    const metres = heights[i] / 10;
    if (metres < lowest) lowest = metres;
    if (metres > highest) highest = metres;
  }

  return new TerrainTile(
    {
      planet,
      originX,
      originZ,
      centreX: originX + ((samples - 1) * spacing) / 2,
      centreZ: originZ + ((samples - 1) * spacing) / 2,
      span: (samples - 1) * spacing,
      spacing,
      samples,
      minHeight: lowest,
      maxHeight: highest,
      height: `${planet}/cut`,
      flags: `${planet}/cut`,
      datum: datumDm / 10,
    },
    heights,
    flags,
  );
}
